/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx,css}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-container": "#fd6c22",
        "surface-container-highest": "#e5e2e1",
        "surface-container-low": "#f6f3f2",
        error: "#ba1a1a",
        "on-primary-fixed-variant": "#38485a",
        outline: "#74777d",
        "primary-fixed": "#d2e4fb",
        "tertiary-fixed-dim": "#6fd8c8",
        "on-tertiary-fixed": "#00201c",
        "on-surface": "#1c1b1b",
        "on-error": "#ffffff",
        "tertiary-fixed": "#8cf5e4",
        "surface-bright": "#fcf9f8",
        "tertiary-container": "#00302b",
        background: "#fcf9f8",
        primary: "#041627",
        "inverse-surface": "#313030",
        "primary-fixed-dim": "#b7c8de",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "primary-container": "#1a2b3c",
        "on-secondary-fixed-variant": "#7d2d00",
        "surface-tint": "#4f6073",
        "on-secondary-container": "#591d00",
        "surface-container": "#f0edec",
        "secondary-fixed": "#ffdbcd",
        "on-tertiary-fixed-variant": "#005048",
        "surface-dim": "#dcd9d9",
        "inverse-primary": "#b7c8de",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#30a193",
        "on-surface-variant": "#44474c",
        "outline-variant": "#c4c6cd",
        "inverse-on-surface": "#f3f0ef",
        "on-primary-container": "#8192a7",
        "on-secondary-fixed": "#360f00",
        "on-background": "#1c1b1b",
        "surface-variant": "#e5e2e1",
        "surface-container-high": "#ebe7e7",
        surface: "#fcf9f8",
        "error-container": "#ffdad6",
        secondary: "#a43d00",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#0b1d2d",
        "secondary-fixed-dim": "#ffb597",
        "on-primary": "#ffffff",
        tertiary: "#001916",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
};
